# Generated by Django 5.1.2 on 2024-11-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('location', models.TextField()),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField(null=True)),
                ('bathrooms', models.IntegerField(null=True)),
                ('parking_space', models.IntegerField(null=True)),
                ('area', models.CharField(max_length=50)),
                ('site_url', models.URLField(max_length=255, null=True)),
                ('image_url', models.URLField(max_length=255, null=True)),
                ('time', models.DateTimeField(null=True)),
            ],
        ),
    ]
